import type { Content } from './types';
import { getGalleryItems } from './gallery';

export const en: Content = {
  ui: {
    nav: {
      home: 'Home',
      profile: 'Profile',
      propositions: 'Value',
      results: 'Results',
      experience: 'Experience',
      gallery: 'Gallery',
      education: 'Education',
      licenses: 'Licenses',
      certs: 'Certifications',
      tools: 'Tools',
      contact: 'Contact',
    },
    navShort: {
      home: 'Home',
      profile: 'Profile',
      propositions: 'Value',
      results: 'Results',
      experience: 'Experience',
      gallery: 'Gallery',
      education: 'Education',
      licenses: 'Licenses',
      certs: 'Certs',
      tools: 'Tools',
      contact: 'Contact',
    },
    cta: {
      viewCv: 'View CV',
      downloadCv: 'Download CV',
      contact: 'Contact',
      whatsapp: 'WhatsApp',
      linkedin: 'LinkedIn',
      seeMore: 'See more',
      seeLess: 'See less',
      backToTop: 'Back to top',
      closeViewer: 'Close viewer',
    },
    hero: {
      availability: 'Immediate availability',
      role: 'Head of Operations, Logistics & Supply Chain',
      industries:
        'Mining · Critical transport · Fuels · Chemicals · Explosives · Oversized loads · Passenger transport · Distribution centers · Operational safety · Mining contracts',
      portraitLabels: ['Executive', 'On site', 'Industrial site 2008'],
      metrics: [
        { value: 25, suffix: '+', label: 'Years in mining' },
        { value: 6000000, suffix: ' km', label: 'Driven yearly' },
        { value: 300, suffix: '+', label: 'Team members led' },
        { value: 100, suffix: '%', label: 'RECSS compliance, 4 years' },
      ],
      summary:
        'Logistics Management Engineer, M.Sc. in Operations & Logistics Management (in progress), graduated postgraduate diplomas in Operations Management and People Management, AN/T Risk Prevention Expert and Army Officer. Experience with BHP, AMSA, Codelco, SQM, ENEX, Komatsu, Orica, Engie and Copec under principal, contractor and subcontractor regimes; KPIs, EBITDA and person/fleet accreditation.',
    },
    sections: {
      profileTitle: 'Professional profile',
      profileEyebrow: 'About me',
      companiesTitle: 'Principals, contracts and operators I have worked with',
      propositionsTitle: 'Value propositions',
      propositionsEyebrow: 'What I offer',
      resultsTitle: 'Recognitions and results',
      resultsEyebrow: 'Measurable impact',
      experienceTitle: 'Professional experience',
      experienceEyebrow: 'Trajectory',
      galleryTitle: 'Professional gallery',
      galleryEyebrow: 'On site',
      galleryIntro:
        'Visual record of field leadership, safety, training and projects with large-scale mining in northern Chile.',
      educationTitle: 'Education',
      educationEyebrow: 'Credentials',
      licensesTitle: 'Driving licenses',
      licensesEyebrow: 'Professional driving',
      certsTitle: 'Certifications and accreditations',
      certsEyebrow: 'High level',
      toolsTitle: 'Tech stack and tools',
      toolsEyebrow: 'Operational stack',
      languagesTitle: 'Languages and availability',
      contactTitle: 'Contact',
      contactEyebrow: 'Let’s talk',
    },
    labels: {
      titled: 'Graduated',
      inProgress: 'In progress',
      completed: 'Completed',
      magna: 'Magna Cum Laude',
      references: 'Strategic professional references available upon request.',
      availability: 'Immediate availability',
      languagesIntro: 'Languages and professional computing',
      based: 'Antofagasta, Chile',
      born: 'Jan 29, 1982',
      yearsOld: 'years old',
      privateContact:
        'Third-party phone numbers are not published on the public portfolio.',
    },
    footer: {
      rights: 'All rights reserved.',
      keywordsLabel: 'Areas of practice',
    },
    gallery: {
      filterAll: 'All',
      filterLiderazgo: 'Leadership',
      filterSeguridad: 'Safety',
      filterAuditoria: 'Audits',
      filterCapacitacion: 'Training',
      filterOperaciones: 'Operations',
      filterProyectos: 'Projects',
      filterAcademia: 'Academia',
      filterMilitar: 'Military',
      filterReconocimiento: 'Recognition',
      filterReuniones: 'Meetings',
      photoCount: 'photos',
      closeLightbox: 'Close',
      prevPhoto: 'Previous',
      nextPhoto: 'Next',
      carouselHint: 'Use the arrow keys, buttons, or thumbnails to browse the {count} photos.',
    },
  },
  reader: {
    quickFactsTitle: 'Executive quick facts',
    quickFacts: [
      { label: 'Base', value: 'Santiago, Chile · Antofagasta' },
      { label: 'Trajectory', value: '25+ years in large-scale mining in northern Chile' },
      { label: 'Sectors', value: 'Mining · fuels · logistics · critical transport' },
      { label: 'Operating model', value: 'Principal · contractor · subcontractor · 24/7 operations' },
      { label: 'Languages', value: 'Native Spanish · technical-operational English' },
      { label: 'Licenses', value: 'SERCAEM A-2 and D · professional driving and machinery' },
    ],
    executiveSummaryEyebrow: 'Reading context',
    executiveSummaryTitle: 'Executive context summary',
    executiveSummaryIntro:
      'This page brings together trajectory, results, education, and operational evidence. It is best read as a leadership and execution profile built on real operations.',
    executiveSummaryPoints: [
      {
        title: 'Environment',
        detail:
          'Career built in large-scale mining, fuels, industrial logistics, critical transport, and distribution centers in northern Chile.',
      },
      {
        title: 'Operating model',
        detail:
          'Experience under principal, contractor, and subcontractor regimes, focused on operational continuity, safety, compliance, and contract control.',
      },
      {
        title: 'Scale',
        detail:
          'Leadership of teams above 300 people, 24/7 operations, critical fleets, branches up to 30,000 m², and inventories above 70,000 SKU.',
      },
    ],
    featuredResultsEyebrow: 'Quick read',
    featuredResultsTitle: 'Key results',
    featuredResultsIntro:
      'Initial selection for recruiters and decision-makers. The full evidence set continues in the grid below.',
    featuredResults: [
      { index: 0, tag: 'Operational safety' },
      { index: 1, tag: 'Logistics scale' },
      { index: 4, tag: 'Critical compliance' },
      { index: 34, tag: 'Contract coverage' },
    ],
    availabilityTitle: 'Available for',
    availabilityIntro:
      'Available for selection processes, executive consulting, and leadership roles that require structuring complex operations, mining contracts, and service continuity with technical and operational backing.',
    availabilityItems: [
      {
        title: 'Operations leadership',
        detail:
          '24/7 operations, branches, distribution centers, fleets, industrial supply, and critical transport leadership.',
      },
      {
        title: 'General contract administration',
        detail:
          'Principal-facing coordination, KPIs, payment control, startup files, accreditation, and contract execution in mining and industrial settings.',
      },
      {
        title: 'Specialized advisory',
        detail:
          'Operational diagnostics, process redesign, document control, compliance, safety, and continuous improvement for logistics and mining services.',
      },
      {
        title: 'Implementation and stabilization',
        detail:
          'Startup, audits, risk control, supply continuity, team leadership, and field-level operational stabilization.',
      },
    ],
    photoLabels: {
      hero: [
        { eyebrow: 'Executive profile', detail: 'Professional trajectory and operational leadership' },
        { eyebrow: 'On site', detail: 'Mining-industrial context and field supervision' },
        { eyebrow: 'Industrial site 2008', detail: 'Historic record of field experience' },
      ],
      profile: { eyebrow: 'Site office', detail: 'Document review and operational control' },
      education: { eyebrow: 'Santiago 2026', detail: 'Postgraduate diploma and academic recognition' },
    },
  },
  profile: [
    'Logistics Management Engineer, M.Sc. in Operations & Logistics Management (in progress), with graduated postgraduate diplomas in Operations Management and People Management & Organizational Change, AN/T Risk Prevention Expert and Chilean Army Officer in Military Sciences.',
    'For over 25 years in northern Chile’s large-scale mining: civic-military operations, logistics infrastructure, chemical plants, multimodal distribution, critical transport, fuels, supply chain, distribution centers and general mining contract administration.',
    'Cross-functional experience with Codelco, Antofagasta Minerals (AMSA), BHP, SQM, ENEX S.A., Komatsu, Hualpén, Viggo/Tur Bus, Michelin, Orica, Enaex, Maxam, Copec and Engie under principal, contractor and subcontractor regimes. Company, people and fleet accreditation processes: SIGA, SERCOL, MyPass, RECSS, onboarding files and contract execution plans.',
    'Specialist in mining contract management, 24/7 operations leadership, branches up to 30,000 m², inventories above 70,000 SKU, port reception, oversized loads, cross docking, FIFO/FEFO/LIFO, SAP, WMS, telemetry and multidisciplinary teams of 300+ people. Regulatory compliance: Law 16,744, Law 20,123, Law 17,798, DS 132, DS 160, DS 148, DS 594, Art. 25 bis, RESPEL/SIDREP, PREXOR, PLANESI and CEAL-SM.',
  ],
  companies: [
    { slug: 'antofagasta-minerals', name: 'AMSA · Antofagasta Minerals' },
    { slug: 'codelco', name: 'Codelco' },
    { slug: 'sqm', name: 'SQM' },
    { slug: 'bhp', name: 'BHP' },
    { slug: 'enex', name: 'ENEX' },
    { slug: 'rcl', name: 'RCL' },
    { slug: 'ati', name: 'ATI' },
    { slug: 'epa', name: 'EPA' },
    { slug: 'puerto-angamos', name: 'Puerto Angamos' },
    { slug: 'komatsu', name: 'Komatsu Cummins' },
    { slug: 'finning', name: 'Finning' },
    { slug: 'michelin', name: 'Michelin' },
    { slug: 'hualpen', name: 'Hualpén' },
    { slug: 'viggo', name: 'Viggo' },
    { slug: 'tur-bus', name: 'Tur Bus' },
    { slug: 'vinara', name: 'Vinara' },
    { slug: 'transportes-cinco', name: 'Transportes 5' },
    { slug: 'cademartori', name: 'Cademartori' },
    { slug: 'copec', name: 'Copec' },
    { slug: 'engie', name: 'Engie' },
    { slug: 'orica', name: 'Orica' },
    { slug: 'enaex', name: 'Enaex' },
    { slug: 'maxam', name: 'Maxam' },
    { slug: 'albemarle', name: 'Albemarle' },
    { slug: 'teck', name: 'Teck' },
    { slug: 'bechtel', name: 'Bechtel' },
    { slug: 'fcab', name: 'FCAB' },
    { slug: 'bureau-veritas', name: 'Bureau Veritas' },
    { slug: 'tuv-rheinland', name: 'TÜV Rheinland' },
    { slug: 'cesmec', name: 'CESMEC' },
  ],
  propositions: [
    {
      icon: 'mountain',
      title: 'End-to-end mining operations leadership',
      description:
        'Logistics, critical transport and supply chain with focus on operational continuity, safety, efficiency, contract compliance and cost control.',
    },
    {
      icon: 'briefcase',
      title: 'General contract administration',
      description:
        'Principal, contractor and subcontractor regimes. KPI management, audits, payment statements, onboarding files and person/fleet accreditation.',
    },
    {
      icon: 'warehouse',
      title: 'Distribution centers and supply chain',
      description:
        'Industrial layout, storage, inventory, port reception, deconsolidation, cross docking, picking, packing, FIFO, FEFO, LIFO, WMS and SAP.',
    },
    {
      icon: 'truck',
      title: 'High-risk fleets and transport',
      description:
        'Fuels, passengers, explosives, chemicals, equipment, mining components, buses, tanker trucks, semi-trailers and oversized loads.',
    },
    {
      icon: 'shield',
      title: 'Operational safety and preventive culture',
      description:
        'Telemetry, fatigue and drowsiness, alcohol and drugs, speeding, mass drills, green indicators, legal compliance and zero accidents.',
    },
    {
      icon: 'users',
      title: 'People leadership and labor relations',
      description:
        'Union negotiation, organizational climate, team building, training and continuous improvement for workforces over 300 people.',
    },
    {
      icon: 'leaf',
      title: 'Sustainability and shared value',
      description:
        'E-mobility, ISO 14001/39001, community campaigns, energy transition and footprint reduction in mining operations.',
    },
    {
      icon: 'chart',
      title: 'Operational digital transformation',
      description:
        'Mobileye, Guardian, Migtra, Wisetrack, digital checklists, passenger control, drowsiness control and contract monitoring platforms.',
    },
  ],
  results: [
    { metric: '0', label: 'STP/CTP/AAP accidents in BHP Spence and AMSA Centinela contracts 2022-2025 (ENEX/RCL)' },
    { metric: '6M km', label: 'Driven yearly with 0% accidents in critical supply operations' },
    { metric: '3M km', label: 'Driven yearly for AMSA Centinela' },
    { metric: '300K m³', label: 'Fuel delivered and 6,000+ shifts yearly to large-scale mining' },
    { metric: '100%', label: 'Critical contractual and legal compliance — monthly RECSS for four consecutive years (ENEX/RCL)' },
    { metric: 'RAEV', label: 'National recognitions 2022-2025: Spence fleet 0.1 · AMSA 0.3 · individual 0.1' },
    {
      metric: 'UNAB',
      label: 'Certificate of recognition for best national academic performance',
      featured: true,
    },
    { metric: 'ENEX Pillars', label: 'Recognitions 2022-2025 with over 95% performance — one of Chile’s safest fleets' },
    { metric: 'CONASET', label: 'Safest fleet in Chile 2022-2025 (CONASET + CONACEP) — BHP and AMSA contracts' },
    { metric: 'CONACEP', label: 'National CONACEP award — safest fleet in Chile (ENEX/RCL)' },
    { metric: '0% mobile', label: '0% mobile-phone deviations on fleet 2022-2025 (ENEX/RCL)' },
    { metric: 'Fatigue ↓', label: 'Sequential reduction in fatigue and drowsiness events 2022-2025' },
    { metric: '100%', label: 'Community campaigns and environmental control with satisfactory results (ENEX/RCL)' },
    { metric: 'Zero loss', label: 'Zero supply losses — Copec Tocopilla operation' },
    { metric: '100% CIP', label: 'Continuous improvement plans validated by clients (Komatsu)' },
    { metric: 'Top 10', label: 'Best drivers in Chile within the fleet via RAEV awards' },
    {
      metric: 'Magna Cum Laude',
      label: 'Magna Cum Laude distinction — Postgraduate Diploma in Operations Management, Universidad Andrés Bello (March 2026)',
      featured: true,
    },
    { metric: 'Centinela', label: 'Safest fuel-supply contract for ENEX/RCL — Minera Centinela (AMSA)' },
    { metric: 'BHP Spence', label: 'Best fleet on BHP Spence contract 2022-2025 with zero STP/CTP accidents' },
    { metric: '90-100%', label: 'TÜV Rheinland audits 2022, 2023, 2024 and 2025' },
    { metric: '100% OHS', label: 'BHP Spence and AMSA Centinela mining audits + 100% in on-site cross audits' },
    { metric: 'Green KPI', label: '100% on green-indicator KPIs and corporate fleet image 2022-2025' },
    { metric: '100% F30', label: '100% F30 and F30-1 compliance — labor and social-security records (HR), FTE BHP, work-hours and license' },
    { metric: 'CLOA/SMAS', label: 'CLOA (BHP) and SMAS (AMSA) accreditation and compliance on ENEX/RCL contracts' },
    { metric: '100% KPI', label: 'Expected KPI compliance for product loading, transfer and unloading' },
    { metric: '100%', label: 'Alcohol/drug control compliance 2022-2025' },
    { metric: 'Drills', label: 'Design and leadership of large-scale fuel drills for mining' },
    { metric: 'Emilia Law', label: 'Recognition for incorporating Zero Tolerance and Emilia Law awareness' },
    { metric: 'BHP CIM', label: 'ENEX representative to BHP Spence for Integrated Contractor Management and Contract Execution Plan' },
    { metric: '+90%', label: 'Improvement in arrival times at Viggo Chile northern zone 2021-2022' },
    { metric: '40% → 0%', label: 'Incident reduction at Viggo northern zone via controls and audits' },
    { metric: '+60%', label: 'Operated volume increase at Viggo + 8-point customer satisfaction gain' },
    { metric: 'First electric', label: 'First fully-electric King Long XMQ 6130 eTech buses (~280 km) for SQM' },
    { metric: '4 ISO', label: 'Four-norm 9001 · 14001 · 45001 · 39001 (Transportes Hualpén)' },
    { metric: '70 contracts', label: '~28% of national portfolio (70 of 250 contracts) led in northern zone with 24/7 operations — Hualpén' },
    { metric: '10,000', label: 'Daily passengers managed in the northern zone (of 75K national)' },
    { metric: 'Hualpén Digital', label: 'Leadership 2019-2021 as digital transformation precursor in northern zone' },
    { metric: '0 accidents', label: 'Calama fleet 2019 (Hualpén)' },
    {
      metric: 'Female inclusion',
      label:
        '8.61% of women in Hualpén national workforce — large-scale incorporation into Codelco contracts and relevant demand in main Calama contracts',
    },
    { metric: '15,000 m²', label: 'Cross-docking layout implemented at Michelin Antofagasta/Mejillones' },
    { metric: '100% ↓', label: 'Safety and environmental incident reduction — Copec Tocopilla' },
    { metric: '30% ↓', label: 'Operational storage cost savings at Copec Tocopilla' },
    { metric: '+90%', label: 'Inventory accuracy at Komatsu Cummins via SAP MMS/WMS + radio-frequency' },
    { metric: '80% ↓', label: 'Logistics cost reduction at CD La Negra (Komatsu)' },
    { metric: '70K+ SKU', label: 'Cummins line part numbers under management (Komatsu)' },
    { metric: 'First CAEX', label: 'Reception and logistics of first autonomous CAEX trucks for Chilean mining' },
    { metric: '90%', label: 'Workforce stability at Komatsu with improvements in food, transport, locker rooms and green areas' },
  ],
  experience: [
    {
      period: 'Dec 2025 – Present',
      role: 'Independent Specialist Engineer · Logistics Operations Advisor',
      company: 'Freelance Project',
      location: 'Industrial mining, transport, DC, machinery and supply chain',
      scope:
        'Specialized advisory in logistics operations for industrial mining, transport, distribution centers, machinery, supply chain, safety and accreditation of companies, people and fleets.',
      highlights: [
        'Support in process design, document control and operational review for mining and industrial services.',
        'Supply continuity, regulatory compliance and operational safety.',
        'Improvement projects, risk control, KPIs, contract control, transport planning and fleet administration.',
      ],
    },
    {
      period: '2022 – 2025',
      role: 'General Project Administrator · Head of Distribution Center and Mining Logistics',
      company: 'ENEX S.A. / RCL S.A.',
      logos: ['enex', 'rcl'],
      location: 'BHP Spence · AMSA Centinela · Nueva Centinela',
      scope:
        'General administration of mining contracts for industrial fuel supply to Minera Centinela AMSA, Nueva Centinela AMSA and BHP Spence; operations in Calama, Antofagasta, Sierra Gorda and Mejillones.',
      highlights: [
        'Fleet of 50+ New Actros 2022-2025 tractor trucks and 70+ semi-trailers; 500,000 km monthly / 6M km yearly.',
        '300,000+ m³ transported yearly and 6,000+ shifts delivered to large-scale mining.',
        'Zero STP/CTP accidents; 100% RECSS compliance for 4 consecutive years; TÜV audits 90-100%.',
        'National RAEV awards 2022-2025 and CONASET/CONACEP recognitions as one of Chile’s safest fleets.',
      ],
      extended: [
        'Secondary contracts: FCAB Calama/Train/Arriero/Mejillones/Antofagasta, Terquim Mejillones, Copec Mejillones, AMSA Esperanza/Esperanza Sur, Minera Encuentro, AMSA Óxido, SX BHP, AMSA Pier and Caleta Michilla plant.',
        'International logistics support for the Albemarle Peru Chemical project and Engie Gas Mining AMSA project.',
        'Representation of ENEX/RCL before principals on costs, compliance, safety, maintenance, payments, KPIs, audits and execution plans.',
        'WRAC EECC, DPRF EECC, RECSS EECC compliance, TC8/TC10 declarations to SEC for fuel tanker trucks (DS160), HSE plan, incident management and alcohol/drug standard.',
        'KPIs: shifts, available trips, real deliveries (oil/EDS/SGO/SX), dropped/rerouted trips, m³ delivered, kilometers, RAEV, Guardian, maintenance, talks and visible leaderships.',
        'Accreditations MyPass, SAR, DLMS, LMS, DBMS, SIGA, SERCOL, AIRON, SAP; platforms Proactive Safety, Guardian, Migtra, Bureau Veritas, FuelTrack, Seeing Machine and Skynav.',
        'CLOA (BHP) and SMAS (AMSA) compliance; BHP Spence CIM (Integrated Contractor Management), Performance Meetings, Contract Execution Plan and AMSA expected behaviors.',
        'Design and direction of large-scale fuel drills for mining with public agencies; recognition for Zero Tolerance and Emilia Laws awareness.',
        'Safety and operations monitor; head of hygiene and safety department; internal auditor for engineering area.',
        '0% mobile-phone deviations; sequential reduction in fatigue and drowsiness between 2022 and 2025.',
        'Community campaigns and environmental control with 100% satisfactory results.',
      ],
    },
    {
      period: '2021 – 2022',
      role: 'Operations Management Viggo Subsidiary · Zonal Branch Manager',
      company: 'Viggo Chile S.A. / Tur Bus',
      logos: ['viggo', 'tur-bus'],
      location: 'Northern Zone · Antofagasta Region',
      scope:
        'Legal and operational responsibility for mining contracts in the northern industrial mining zone, transport, fleets, maintenance, safety, logistics and KPIs.',
      highlights: [
        'Mining contracts: Atacama Minerals, CTTO Lots, Finning MEL, Molyb (Codelco subsidiary), Caserones, SAM, Orica Chile, FCAB, Toconao SQM, Excon and Franke.',
        '150 Mercedes-Benz O-500 RS/RSD buses with Irizar i6 and Busscar bodies; 150 Sprinter 516 and Vito; first 100% electric Sprinters with 60 kWh batteries.',
        'Antofagasta branch of 30,000+ m² with 300+ employees; 500,000 km monthly in large-scale mining.',
      ],
      extended: [
        'Incident reduction from 40% to 0% via control programs, audits and corrective actions.',
        'Over 90% improvement in arrival times and operational cost reduction up to 80% via route optimization.',
        '100% audit and SLA compliance on key contracts; +60% operated volume via fleet and coverage expansion.',
        'Deployment of first fully-electric King Long XMQ 6130 eTech buses (~280 km autonomy) for SQM.',
        'Giro Limpio SQM seal, GTP Academia, GTP BCN School of Business, Viggo Leadership Program and 5 Operational Driving Rules.',
        'GTP — Passenger Transport Group; experience with Scania chassis and Marcopolo bodies.',
        '100% implementation of Art. 25 controls, speeding, alcohol/drugs, fatigue and fleet monitoring platforms.',
      ],
    },
    {
      period: '2019 – 2021',
      role: 'Zonal Operations Manager Region II · Acting DC Manager',
      company: 'Transportes Hualpén S.A.',
      logos: ['hualpen'],
      location: 'Calama · Antofagasta · Iquique · Tarapacá',
      scope:
        'Operations management, industrial mining passenger transport in the northern industrial mining zone, distribution, maintenance, logistics, fleet control and contract administration.',
      highlights: [
        '70 northern-zone contracts (out of 250 nationally) with 24/7 operations for large-scale mining; 10,000 daily passengers under management.',
        'Mercedes-Benz O-500 RS/RSD, Scania, Yutong, Volvo, Marcopolo, King Long fleets; 300 buses, 100 Sprinters, 150 minibuses, 150 microbuses.',
        'ISO 39001 Road Safety certification adding the four-norm with ISO 9001/14001/45001.',
      ],
      extended: [
        'Contracts: Finning, Enaex, Codelco Gabriela Mistral, Komatsu, CVV, Chuquicamata, Ministro Hales, Albemarle, Teck QB1/QB2, Bechtel, Compass Group, Sodexo and Besalco.',
        'Incident reduction 90% and operational cost reduction 60% with availability and efficiency KPIs.',
        'Adoption of Mobileye, telemetry, traffic control, passenger control, drowsiness control and digital checklists.',
        'First Hualpén 2020 sustainability report; precursor of e-mobility and renewables in the northern zone.',
        'Drivers School in Calama with unions; large-scale incorporation of women into Codelco contracts, reaching 8.61% of women in the national workforce and relevant demand in main Calama contracts.',
        'Zero accidents in Calama fleet 2019; participation in Hualpén Digital 2019-2021 digital transformation.',
        'Oversight of 100+ mining and local contracts, 14 risk prevention officers and 10 contract administrators.',
        'EBITDA compliance, board reporting and Hualpén Service attributes: safety, comfort, innovation, punctuality and technology.',
        'Drivers School in Calama with Automóvil Club de Chile certification.',
      ],
    },
    {
      period: '2018 – 2019',
      role: 'Operations Manager Distribution Center',
      company: 'Michelin / Hellmann International / Cademartori',
      logos: ['michelin', 'ati', 'epa', 'puerto-angamos'],
      location: 'Antofagasta · Mejillones',
      scope:
        'Port reception, deconsolidation, storage and distribution of tires for mining equipment and components.',
      highlights: [
        '30,000+ m² branch with 250+ external carriers, administration and plant staff.',
        'Implementation of automated stock control and 15,000 m² cross-docking layout.',
        'Advisory on Michelin International Industrial Rubber Waste Mega Project.',
      ],
      extended: [
        'Port management ATI, EPA, Puerto Angamos (PA) and SAA; stowage of 40 ft containers, Open Top, lowboys and oversized loads.',
        'Cost control and application of Incoterms EXW/FCA/CPT/CIP/DAP/DPU/DDP/FAS/FOB/CFR/CIF.',
        '20/40 ft, Dry Van, Reefer, High Cube, Open Top, Flat Rack and Tank containers.',
        'Compliance with Law 20,123, Law 16,744, DS 594 and DS 148; SIDREP management and accident KPIs.',
        'Layout for Michelin XDR3 59/80R63 tire (CAT 797B), 4.2 m diameter, stock above 1,000 units.',
      ],
    },
    {
      period: '2014 – 2017',
      role: 'Manager · Operations Deputy Manager · Regional Operations Head',
      company: 'Orica Chile · Enaex · Maxam · Vinara · Transportes Cinco',
      logos: ['orica', 'enaex', 'maxam', 'vinara', 'transportes-cinco'],
      location: 'Antofagasta Region',
      scope:
        'Port reception, deconsolidation, storage and distribution of explosives and detonators under Law 17,798 on Arms and Explosives Control.',
      highlights: [
        'Contract transition from Transportes Cinco (15,000 m²) to Vinara (30,000 m²) with client-requested continuity.',
        'Leadership of multidisciplinary 100+ teams under high-pressure 24/7 operations.',
        'Convoy coordination with armed escort (former Armed Forces and police) under Free Transit Guides.',
      ],
      extended: [
        'Contracts: Orica Chile and SPOT services for Minera Centinela, Zaldívar, Antucoya and Polytex.',
        'Stock control and traceability of Cordtex, Exel, Pentex, electric detonators and EBS, 4D, WebGen and RHINO technologies.',
        'Custody of gasified emulsions, high-risk chemicals and cyanide under national security protocols.',
        'Waste management per DS 148/2003 MINSAL; supervision of reach stackers, forklifts and explosive transport trucks.',
        'OTIF, safety, fleet availability, overhead, operating budgets and profitability KPIs.',
      ],
    },
    {
      period: '2011 – 2013',
      role: 'Plant and DC Head · Operations and Supply Management',
      company: 'Copec S.A. / Engie',
      logos: ['copec', 'engie'],
      location: 'Tocopilla',
      scope:
        'Operations, transport and supply of liquid fuels for large-scale mining and energy sectors.',
      highlights: [
        '30,000 m² branch and plant with 100+ employees; loading/unloading of tanker ships at PC6 Banker Port.',
        '100% reduction in safety and environmental incidents; 30% operational cost savings.',
        'Strategic Copec-mining alliance with corporate representation in Tocopilla.',
      ],
      extended: [
        'Implementation of DS 160 liquid fuels, DS 148 hazardous waste and Law 16,744 OHS.',
        'Stock and traceability of diesel, PC6, JET A1 and industrial lubricants.',
        'Measurements in vertical tanks for supply to generating plants and mining sites.',
        'Modernization of fuel facilities and 24/7 customer service.',
        'Zero supply losses; pumping operations at PC6 Banker maritime terminals.',
        'Active representation of Copec S.A. in Tocopilla and shared socioeconomic value with the community.',
      ],
    },
    {
      period: '2008 – 2011',
      role: 'Distribution Center Operations Head – Northern Zone',
      company: 'Komatsu Cummins Chile S.A.',
      logos: ['komatsu'],
      location: 'Antofagasta',
      scope:
        'Operations management for port reception, deconsolidation, storage and distribution of equipment, components and critical spare parts for large-scale mining.',
      highlights: [
        '70,000+ Cummins line part numbers under management; 90% improvement in inventory accuracy via RF.',
        'SAP MMS/WMS and radio-frequency implementation; 80% logistics cost reduction at CD La Negra.',
        'Logistics and reception of the first CAEX autonomous trucks for Chilean mining.',
      ],
      extended: [
        'Strategic transfer CD La Portada Norte → CD La Negra → CD La Portada Antofagasta.',
        'Supervision of 5,000 m² for major components and disassembly; assembly, transfer, yard and final delivery.',
        '90% workforce stability with improvements in food, transport, locker rooms and green areas.',
        'Lean Logistics: shelving, racks, cross docking, picking, packing, FIFO, LIFO, FEFO and OTIF.',
        'One Step Ahead program; internal certification on high-tonnage equipment (3.5 to 15 tons).',
        'KPI and CAPEX management; 100% compliance on continuous improvement plans validated by strategic clients.',
        'Reverse logistics, remanufacturing and internal certification on 3.5 to 15 ton equipment.',
      ],
    },
    {
      period: '2005 – 2008',
      role: 'Plant Operations Lead · Finished Products Operations Management',
      company: 'SQM – Sociedad Química y Minera de Chile S.A.',
      logos: ['sqm'],
      location: 'Coya Sur · María Elena · Pedro de Valdivia · Tocopilla Port',
      scope:
        'Multimodal land, rail and port operations for raw-material reception, storage and international distribution of nitrates and sulfates.',
      highlights: [
        'Prilling, Sulfate, Granulation, KCL, KNO3 Drying plants, stockpiles and Tocopilla Port.',
        'Rail, truck and maritime dispatch coordination for export.',
      ],
      extended: [
        'Stock management and dispatch of KNO3, KCL, sulfates and NPK fertilizers.',
        'Chemical safety protocols, industrial cleaning and cross-contamination prevention.',
        'Control-room leadership with critical-variable monitoring, sampling and real-time chemical analysis.',
        'Coordination of conveyor belts, high-capacity trains, industrial dryers and high-speed bagging.',
      ],
    },
    {
      period: 'Military training · Graduated with highest distinction',
      timelineMark: '0',
      role: 'Chilean Army Officer in Military Sciences',
      company: 'Chilean Army',
      logos: ['ejercito-chile'],
      location: 'Chile',
      scope:
        'Training and service as Army Officer in Military Sciences in the Chilean Army; graduated with highest distinction. Foundation of career in civic-military operations, logistics, transport and supply.',
      highlights: [
        'Intendance, Intelligence, logistics, transport, supply, supply chain and operations.',
        'Graduated with highest distinction — Chilean Army Officer in Military Sciences.',
        'Civic-military operations and logistics infrastructure as foundation of career in northern Chile large-scale mining.',
      ],
      extended: [
        'Training in intendance, intelligence, military logistics, transport, supply and supply chain operations.',
        'Foundation for leadership in high-demand operations, operational discipline and service continuity.',
      ],
    },
  ],
  gallery: getGalleryItems('en'),
  education: [
    {
      title: 'M.Sc. in Operations & Logistics Management',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2024 – 2026',
      status: 'in_progress',
      detail: 'Graduate degree, Faculty of Education and Social Sciences. File 3320571. Estimated completion: November 2026.',
    },
    {
      title: 'Postgraduate Diploma in People Management and Organizational Change',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2023 – 2024',
      status: 'titled',
      detail:
        'Postgraduate diploma, Faculty of Education and Social Sciences. Registry 588/2023, Reg. 2024 N°7031. Graduated with highest distinction.',
      recognition: 'Certificate of recognition for best national academic performance.',
    },
    {
      title: 'Postgraduate Diploma in Logistics Management and Supply Chain',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2025 – 2026',
      status: 'in_progress',
      detail: 'Postgraduate diploma, Faculty of Engineering. File 3320571. Estimated completion: August 2026.',
    },
    {
      title: 'Postgraduate Diploma in Leadership for Innovation',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2025 – 2026',
      status: 'in_progress',
      detail: 'Postgraduate diploma, Faculty of Engineering. File 3320571. Estimated completion: November 2026.',
    },
    {
      title: 'Postgraduate Diploma in Operations Management',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2025 – 2026',
      status: 'titled',
      magna: true,
      detail: 'Postgraduate diploma, Faculty of Engineering. File 3789769. Graduated March 2026.',
      recognition: 'Magna Cum Laude distinction',
      recognitionDetail:
        'Highest academic honor of the postgraduate diploma. Magna Cum Laude is an internationally recognized university distinction for graduates with exceptional performance: sustained excellence and a grade point average well above the program standard. On the classical academic honors scale it ranks above cum laude; for this diploma it certified the highest level of distinction awarded.',
    },
    {
      title: 'Chilean Army Officer in Military Sciences',
      institution: 'Chilean Army',
      logo: 'ejercito-chile',
      status: 'titled',
      detail:
        'Intendance, Intelligence, logistics, transport, supply, supply chain and operations. Graduated with highest distinction.',
    },
    {
      title: 'Logistics Management Engineer',
      institution: 'Universidad Estatal Arturo Prat',
      logo: 'unap',
      status: 'titled',
      detail: 'Faculty of Business Sciences. Registry 19303029. Graduated with highest distinction.',
    },
    {
      title: 'AN/T Risk Prevention Expert',
      institution: 'Universidad Andrés Bello / AIEP',
      logo: 'unab',
      status: 'titled',
      detail: 'School of Engineering and Construction. Registry 105792. Res. 3314 SNS AN/T-4431. Graduated with highest distinction.',
    },
    {
      title: 'Electromechanical Technician',
      institution: 'Liceo Técnico Profesional María Egaña',
      status: 'titled',
      detail: 'Technical-professional secondary education. Graduated with highest distinction.',
    },
    {
      title: 'Primary Education',
      institution: 'Colegio Unión Nacional Árabe',
      status: 'completed',
      detail: 'Primary school completed.',
    },
  ],
  drivingLicenses: [
    {
      license: 'Class A-2 license',
      description:
        'Professional SERCAEM driving license — cargo vehicles, critical transport and industrial operations.',
    },
    {
      license: 'Class D license',
      description:
        'Professional SERCAEM driving license — heavy self-propelled machinery: tractors, forklifts, backhoes, mechanical shovels, graders and bulldozers. Does not authorize cars, vans or motorcycles.',
    },
  ],
  certifications: [
    {
      category: 'Mining and engineering accreditations',
      items: [
        'Specialist Engineer in CAS Systems for critical transport, fuel, passenger and chemical fleets.',
        'Expert Engineer in BHP/AMSA Accreditation: SIGA, RECSS Centinela, Aureon, MyPass, LMS and SAR.',
        'SERCOL BHP/AMSA Expert in subcontractor management and CEP onboarding files.',
        'Administrator of BHP DBMS/iButton, PSGCC, PTP and SKYNAV for identity and driving control.',
        'Company, people and fleet accreditation processes on mining platforms.',
      ],
    },
    {
      category: 'Technical certifications and heavy machinery',
      items: [
        'UATSA Monitor Engineer (University of Antofagasta): front loaders, backhoes and forklifts 3-15 tons.',
        'Specialist operator in Reach Stackers, electric stackers for 12 m racks and UATSA forklifts.',
        'Instructor on the 5 Operational Driving Rules.',
      ],
    },
    {
      category: 'Regulations and legal compliance',
      items: [
        'Law 16,744 (occupational accidents and diseases), Law 20,123 (subcontracting), Law 17,798 (explosives).',
        'Karin Law (Law 21,643 — workplace harassment, violence and discrimination).',
        'DS 132, DS 160 (Art. 184 — fuel tanker compartments), DS 148, DS 594, DS 40 (Art. 21).',
        'Art. 25 bis and Art. 22 bis; RESPEL, SIDREP, WRAC, DPRF, RECSS, PREXOR, PLANESI, CEAL-SM, HCR, SSO and HSE.',
        'Internal SGI Auditor: ISO 9001, ISO 14001 and OHSAS 18001.',
        'PREXOR (noise), PLANESI (silicosis) and CEAL-SM psychosocial risk protocols.',
        'Instructor on defensive driving, critical behaviors and CELACOP self-protection.',
        'Specialist in fatigue, drowsiness, UV, thermal, road risks and operational continuity prevention.',
      ],
    },
    {
      category: 'ISO management systems',
      items: [
        'ISO 9001 Quality.',
        'ISO 14001 Environment.',
        'ISO 45001 Occupational Health and Safety.',
        'ISO 39001 Road Safety.',
        'Certified internal auditor.',
      ],
    },
    {
      category: 'Strategic leadership and change management',
      items: [
        'Viggo Executive Leadership Program: Accountability, Agile Methodologies, Ethics, Digital Transformation.',
        'GTP Academia and GTP BCN School of Business: ethics, digital transformation, agile methodologies and accountability.',
        'Hualpén Digital Change Management.',
        'Organizational Development and Labor Relations — subcontractor hiring workshops and UATSA techniques.',
      ],
    },
  ],
  tools: [
    {
      category: 'ERP and logistics systems',
      items: [
        'SAP expert level: SAP MM, SAP PM, SAP WMS, SAP FI, SAP MMS/WMS, SAP Business One, RF radio-frequency, locations, SKU control, write-offs and traceability.',
        'SAP transactions LT12 (WM transfer order confirmation), LT15 (TO cancellation) and MIGO (goods movements: receipts, issues and transfers).',
        'ERP BERMAT, Bertrams, Rumba Logistics, Informat and Simatrans.',
        'WMS, cyclical/blind/quarterly/half-year/annual inventories, picking, packing, cross docking, FIFO, FEFO, LIFO and OTIF.',
      ],
    },
    {
      category: 'Telemetry, proactive safety and fleet control',
      items: [
        'Guardian Seeing Machines (fatigue and drowsiness).',
        'SQM REP technology (3 years of professional plant operations experience).',
        'Control rooms: critical variables, process reporting and production continuity.',
        'Migtra (tactical navigator and operational control).',
        'Wisetrack, FuelTrack, Skynav, Mobileye, DBMS/iButton and RAEV systems.',
        'Hazardous substance control with FuelTrack for fuel and acid tankers.',
        'Speed, mobile use, alcohol/drugs control, digital checklists, passenger control, georeferencing, trip planning and travel letters.',
      ],
    },
    {
      category: 'Mining and accreditation platforms',
      items: [
        'MyPass, SAR, DLMS, LMS, DBMS, SIGA, SERCOL, AIRON.',
        'CESMEC, Bureau Veritas, TÜV Rheinland.',
        'CAS, Araya and Briones controls, Directic AMSA, RECSS, PGR, PSGCC, PTP and CC.',
      ],
    },
    {
      category: 'Ports, containers and special cargo',
      items: [
        'ATI, EPA, Puerto Angamos (PA) and SAA terminals — port reception and deconsolidation.',
        'Stowage of 40 ft containers, Open Top, Flat Rack, Dry Van, Reefer and High Cube.',
        'Lowboys, oversized loads, industrial piping and large-dimension tires.',
        'Incoterms EXW, FCA, CPT, CIP, DAP, DPU, DDP, FAS, FOB, CFR and CIF.',
      ],
    },
    {
      category: 'Professional computing',
      items: [
        'Advanced Microsoft Excel — reporting and KPI analysis.',
        'Advanced Microsoft Word and Outlook — operational management and indicator tracking.',
      ],
    },
  ],
  languages: [
    'Spanish: native.',
    'English: medium conversational, high level for technical translation.',
  ],
};
