import type { Content } from './types';
import { getGalleryItems } from './gallery';

export const es: Content = {
  ui: {
    nav: {
      home: 'Inicio',
      profile: 'Perfil',
      propositions: 'Propuestas',
      results: 'Resultados',
      experience: 'Experiencia',
      gallery: 'Galería',
      education: 'Formación',
      licenses: 'Licencias',
      certs: 'Certificaciones',
      tools: 'Herramientas',
      contact: 'Contacto',
    },
    navShort: {
      home: 'Inicio',
      profile: 'Perfil',
      propositions: 'Propuestas',
      results: 'Resultados',
      experience: 'Experiencia',
      gallery: 'Galería',
      education: 'Formación',
      licenses: 'Licencias',
      certs: 'Certific.',
      tools: 'Herram.',
      contact: 'Contacto',
    },
    cta: {
      viewCv: 'Ver CV',
      downloadCv: 'Descargar CV',
      contact: 'Contactar',
      whatsapp: 'WhatsApp',
      linkedin: 'LinkedIn',
      seeMore: 'Ver más',
      seeLess: 'Ver menos',
      backToTop: 'Volver arriba',
      closeViewer: 'Cerrar visor',
    },
    hero: {
      availability: 'Disponibilidad inmediata',
      role: 'Gerente de Operaciones, Logística y Supply Chain',
      industries:
        'Minería · Transporte crítico · Combustibles · Químicos · Explosivos · Cargas sobredimensionadas · Transporte de pasajeros · Centros de distribución · Seguridad operacional · Contratos mineros',
      portraitLabels: ['Ejecutivo', 'En operación', 'Obra industrial 2008'],
      metrics: [
        { value: 25, suffix: '+', label: 'Años en la minería' },
        { value: 6000000, suffix: ' km', label: 'Recorridos anuales' },
        { value: 300, suffix: '+', label: 'Colaboradores liderados' },
        { value: 100, suffix: '%', label: 'Cumplimiento RECSS 4 años' },
      ],
      summary:
        'Ingeniero en Administración Logística, Magíster en Dirección de Operaciones y Logística (en curso), diplomados titulados en Dirección de Operaciones y Gestión de Personas, Experto AN/T en Prevención de Riesgos y Oficial de Ejército. Trayectoria con BHP, AMSA, Codelco, SQM, ENEX, Komatsu, Orica, Engie y Copec en regímenes de mandante, contratista y subcontratista; KPI, EBITDA y acreditación de personas y flotas.',
    },
    sections: {
      profileTitle: 'Perfil profesional',
      profileEyebrow: 'Quién soy',
      companiesTitle: 'Mandantes, contratos y operadores con los que he trabajado',
      propositionsTitle: 'Propuestas de valor',
      propositionsEyebrow: 'Qué ofrezco',
      resultsTitle: 'Reconocimientos y resultados',
      resultsEyebrow: 'Impacto medible',
      experienceTitle: 'Experiencia profesional',
      experienceEyebrow: 'Trayectoria',
      galleryTitle: 'Galería profesional',
      galleryEyebrow: 'En terreno',
      galleryIntro:
        'Registro visual de liderazgo en operaciones, seguridad, capacitación y proyectos con la gran minería del norte de Chile.',
      educationTitle: 'Formación académica',
      educationEyebrow: 'Credenciales',
      licensesTitle: 'Licencias de conducir',
      licensesEyebrow: 'Conducción profesional',
      certsTitle: 'Certificaciones y acreditaciones',
      certsEyebrow: 'Alto nivel',
      toolsTitle: 'Dominio tecnológico y herramientas',
      toolsEyebrow: 'Stack operacional',
      languagesTitle: 'Idiomas y disponibilidad',
      contactTitle: 'Contacto',
      contactEyebrow: 'Hablemos',
    },
    labels: {
      titled: 'Titulado',
      inProgress: 'En curso',
      completed: 'Completado',
      magna: 'Magna Cum Laude',
      references: 'Referencias laborales estratégicas disponibles a solicitud.',
      availability: 'Disponibilidad inmediata',
      languagesIntro: 'Idiomas e informática profesional',
      based: 'Santiago de Chile • Antofagasta',
      born: '29 enero 1982',
      yearsOld: 'años',
      privateContact:
        'Para portafolio web público no se publican teléfonos de terceros.',
    },
    footer: {
      rights: 'Todos los derechos reservados.',
      keywordsLabel: 'Áreas de práctica',
    },
    gallery: {
      filterAll: 'Todas',
      filterLiderazgo: 'Liderazgo',
      filterSeguridad: 'Seguridad',
      filterAuditoria: 'Auditoría',
      filterCapacitacion: 'Capacitación',
      filterOperaciones: 'Operaciones',
      filterProyectos: 'Proyectos',
      filterAcademia: 'Academia',
      filterMilitar: 'Militar',
      filterReconocimiento: 'Reconocimiento',
      filterReuniones: 'Reuniones',
      photoCount: 'fotos',
      closeLightbox: 'Cerrar',
      prevPhoto: 'Anterior',
      nextPhoto: 'Siguiente',
      carouselHint: 'Usa las flechas, los botones o las miniaturas para recorrer las {count} fotos.',
    },
  },
  reader: {
    quickFactsTitle: 'Ficha ejecutiva rápida',
    quickFacts: [
      { label: 'Base', value: 'Santiago de Chile · Antofagasta' },
      { label: 'Trayectoria', value: '25+ años en gran minería del norte de Chile' },
      { label: 'Sectores', value: 'Minería · combustibles · logística · transporte crítico' },
      { label: 'Operación', value: 'Mandante · contratista · subcontratista · operación 24/7' },
      { label: 'Idiomas', value: 'Español nativo · inglés técnico-operacional' },
      { label: 'Licencias', value: 'SERCAEM A-2 y D · conducción profesional y maquinaria' },
    ],
    executiveSummaryEyebrow: 'Contexto de lectura',
    executiveSummaryTitle: 'Resumen ejecutivo de contexto',
    executiveSummaryIntro:
      'Esta página reúne trayectoria, resultados, formación y evidencia operacional. La clave es leerla como un perfil de dirección y ejecución sobre operaciones reales.',
    executiveSummaryPoints: [
      {
        title: 'Entorno',
        detail:
          'Trayectoria en gran minería, combustibles, logística industrial, transporte crítico y centros de distribución del norte de Chile.',
      },
      {
        title: 'Modelo de trabajo',
        detail:
          'Experiencia bajo regímenes de mandante, contratista y subcontratista, con foco en continuidad operacional, seguridad, cumplimiento y control contractual.',
      },
      {
        title: 'Escala',
        detail:
          'Liderazgo de equipos sobre 300 personas, operación 24/7, flotas críticas, sucursales de hasta 30.000 m² e inventarios sobre 70.000 SKU.',
      },
    ],
    featuredResultsEyebrow: 'Lectura rápida',
    featuredResultsTitle: 'Resultados clave',
    featuredResultsIntro:
      'Selección inicial para reclutadores y tomadores de decisión. El detalle completo continúa en la grilla siguiente.',
    featuredResults: [
      { index: 0, tag: 'Seguridad operacional' },
      { index: 1, tag: 'Escala logística' },
      { index: 4, tag: 'Cumplimiento crítico' },
      { index: 34, tag: 'Cobertura contractual' },
    ],
    availabilityTitle: 'Disponibilidad para',
    availabilityIntro:
      'Disponible para procesos de selección, consultoría ejecutiva y roles de liderazgo donde se requiera ordenar operaciones complejas, contratos mineros y continuidad de servicio con respaldo técnico y operacional.',
    availabilityItems: [
      {
        title: 'Dirección de operaciones',
        detail:
          'Liderazgo de operaciones 24/7, sucursales, centros de distribución, flotas, abastecimiento industrial y transporte crítico.',
      },
      {
        title: 'Administración general de contratos',
        detail:
          'Relación con mandantes, KPI, estados de pago, carpetas de arranque, acreditación y ejecución contractual en entornos mineros e industriales.',
      },
      {
        title: 'Asesoría especializada',
        detail:
          'Diagnóstico operacional, rediseño de procesos, control documental, cumplimiento, seguridad y mejora continua para servicios logísticos y mineros.',
      },
      {
        title: 'Implementación y estabilización',
        detail:
          'Puesta en marcha, auditorías, control de riesgos, continuidad de suministro, liderazgo de equipos y ordenamiento de operación en terreno.',
      },
    ],
    photoLabels: {
      hero: [
        { eyebrow: 'Perfil ejecutivo', detail: 'Trayectoria profesional y liderazgo operacional' },
        { eyebrow: 'En operación', detail: 'Contexto minero-industrial y supervisión en terreno' },
        { eyebrow: 'Obra industrial 2008', detail: 'Registro histórico de experiencia en faena' },
      ],
      profile: { eyebrow: 'Oficina de obra', detail: 'Revisión documental y control operacional' },
      education: { eyebrow: 'Santiago 2026', detail: 'Diplomado y reconocimiento académico' },
    },
  },
  profile: [
    'Profesional Ingeniero en Administración Logística, Magíster en Dirección de Operaciones y Logística en curso, con diplomados titulados en Dirección de Operaciones y Gestión de Personas y Cambio Organizacional, Experto AN/T en Prevención de Riesgos y Oficial de Ejército de Chile en Ciencias Militares.',
    'Desde hace más de 25 años en la Gran Minería del norte de Chile: operaciones cívico-militares, infraestructura logística, plantas químicas, distribución multimodal, transporte crítico, combustibles, cadena de suministro, centros de distribución y administración general de contratos mineros.',
    'Experiencia transversal con Codelco, Antofagasta Minerals (AMSA), BHP, SQM, ENEX S.A., Komatsu, Hualpén, Viggo/Tur Bus, Michelin, Orica, Enaex, Maxam, Copec y Engie, bajo regímenes de mandante, contratista y subcontratista. Procesos de acreditación de empresas, personas y flotas: SIGA, SERCOL, MyPass, RECSS, carpetas de arranque y planes de ejecución de contratos.',
    'Especialista en administración general de contratos mineros, dirección de operaciones 24/7, sucursales desde 30.000 m², inventarios sobre 70.000 SKU, recepción portuaria, cargas sobredimensionadas, cross docking, FIFO/FEFO/LIFO, SAP, WMS, telemetría y liderazgo de equipos multidisciplinarios sobre 300 personas. Cumplimiento normativo: Ley 16.744, Ley 20.123, Ley 17.798, DS 132, DS 160, DS 148, DS 594, Art. 25 bis, RESPEL/SIDREP, PREXOR, PLANESI y CEAL-SM.',
  ],
  companies: [
    { slug: 'antofagasta-minerals', name: 'AMSA · Antofagasta Minerals' },
    { slug: 'codelco', name: 'Codelco' },
    { slug: 'sqm', name: 'SQM' },
    { slug: 'bhp', name: 'BHP' },
    { slug: 'enex', name: 'ENEX' },
    { slug: 'rcl', name: 'RCL' },
    { slug: 'ati', name: 'ATI' },
    { slug: 'epa', name: 'EPA' },
    { slug: 'puerto-angamos', name: 'Puerto Angamos' },
    { slug: 'komatsu', name: 'Komatsu Cummins' },
    { slug: 'finning', name: 'Finning' },
    { slug: 'michelin', name: 'Michelin' },
    { slug: 'hualpen', name: 'Hualpén' },
    { slug: 'viggo', name: 'Viggo' },
    { slug: 'tur-bus', name: 'Tur Bus' },
    { slug: 'vinara', name: 'Vinara' },
    { slug: 'transportes-cinco', name: 'Transportes 5' },
    { slug: 'cademartori', name: 'Cademartori' },
    { slug: 'copec', name: 'Copec' },
    { slug: 'engie', name: 'Engie' },
    { slug: 'orica', name: 'Orica' },
    { slug: 'enaex', name: 'Enaex' },
    { slug: 'maxam', name: 'Maxam' },
    { slug: 'albemarle', name: 'Albemarle' },
    { slug: 'teck', name: 'Teck' },
    { slug: 'bechtel', name: 'Bechtel' },
    { slug: 'fcab', name: 'FCAB' },
    { slug: 'bureau-veritas', name: 'Bureau Veritas' },
    { slug: 'tuv-rheinland', name: 'TÜV Rheinland' },
    { slug: 'cesmec', name: 'CESMEC' },
  ],
  propositions: [
    {
      icon: 'mountain',
      title: 'Dirección integral de operaciones mineras',
      description:
        'Logística, transporte crítico y cadena de suministro con foco en continuidad operacional, seguridad, eficiencia, cumplimiento contractual y control de costos.',
    },
    {
      icon: 'briefcase',
      title: 'Administración general de contratos',
      description:
        'Régimen mandante, contratista y subcontratista. Gestión de KPI, auditorías, estados de pago, carpetas de arranque y acreditación de personas/flotas.',
    },
    {
      icon: 'warehouse',
      title: 'Centros de distribución y cadena de suministro',
      description:
        'Layout industrial, almacenamiento, inventarios, recepción portuaria, desconsolidación, cross docking, picking, packing, FIFO, FEFO, LIFO, WMS y SAP.',
    },
    {
      icon: 'truck',
      title: 'Flotas y transporte de alto riesgo',
      description:
        'Combustibles, pasajeros, explosivos, químicos, equipos, componentes mineros, buses, camiones tanque, semirremolques y cargas sobredimensionadas.',
    },
    {
      icon: 'shield',
      title: 'Seguridad operacional y cultura preventiva',
      description:
        'Telemetría, fatiga y somnolencia, alcohol y drogas, velocidad, simulacros masivos, indicadores verdes, cumplimiento legal y cero accidentes.',
    },
    {
      icon: 'users',
      title: 'Dirección de personas y relaciones laborales',
      description:
        'Negociación sindical, clima organizacional, formación de equipos, capacitación y mejora continua de dotaciones sobre 300 colaboradores.',
    },
    {
      icon: 'leaf',
      title: 'Sostenibilidad y valor compartido',
      description:
        'Electromovilidad, ISO 14001/39001, campañas comunitarias, transición energética y reducción de huella en operaciones mineras.',
    },
    {
      icon: 'chart',
      title: 'Transformación digital operacional',
      description:
        'Mobileye, Guardian, Migtra, Wisetrack, checklist digital, control de pasajeros, somnolencia y plataformas de seguimiento contractual.',
    },
  ],
  results: [
    { metric: '0', label: 'Accidentes STP/CTP/AAP en contratos BHP Spence y AMSA Centinela 2022-2025 (ENEX/RCL)' },
    { metric: '6M km', label: 'Recorridos anuales con 0% accidentabilidad en operaciones críticas de suministro' },
    { metric: '3M km', label: 'Recorridos anuales para AMSA Centinela' },
    { metric: '300K m³', label: 'Combustible entregado y 6.000+ turnos anuales a la gran minería' },
    { metric: '100%', label: 'Cumplimiento contractual y legal crítico RECSS mensual durante cuatro años consecutivos ENEX/RCL' },
    { metric: 'RAEV', label: 'Reconocimiento Nacional 2022-2025: flota Spence 0,1 · AMSA 0,3 · individual 0,1' },
    {
      metric: 'UNAB',
      label: 'Certificado de reconocimiento a mejor rendimiento académico nacional',
      featured: true,
    },
    { metric: 'Pilares ENEX', label: 'Reconocimientos 2022-2025 con desempeño sobre 95% — una de las flotas más seguras de Chile' },
    { metric: 'CONASET', label: 'Flota más segura de Chile 2022-2025 (CONASET + CONACEP) — contratos BHP y AMSA' },
    { metric: 'CONACEP', label: 'Premio Nacional CONACEP — flota más segura de Chile (ENEX/RCL)' },
    { metric: '0% celular', label: '0% desviaciones por uso de celular en flota 2022-2025 (ENEX/RCL)' },
    { metric: 'Fatiga ↓', label: 'Reducción secuencial de eventos de fatiga y somnolencia 2022-2025' },
    { metric: '100%', label: 'Campañas comunitarias y control de medio ambiente con resultados satisfactorios (ENEX/RCL)' },
    { metric: '0 pérdidas', label: 'Cero pérdidas en abastecimiento — operación Copec Tocopilla' },
    { metric: '100% PMI', label: 'Cumplimiento de planes de mejoramiento continuo validados por clientes (Komatsu)' },
    { metric: 'Top 10', label: 'Mejores conductores de Chile dentro de la flota por premios RAEV' },
    {
      metric: 'Magna Cum Laude',
      label: 'Distinción Magna Cum Laude — Diplomado en Dirección de Operaciones, Universidad Andrés Bello (marzo 2026)',
      featured: true,
    },
    { metric: 'Centinela', label: 'Contrato más seguro en abastecimiento de combustible ENEX/RCL — Minera Centinela (AMSA)' },
    { metric: 'BHP Spence', label: 'Mejor flota del contrato BHP Spence 2022-2025 con cero accidentes STP/CTP' },
    { metric: '90-100%', label: 'Auditorías TÜV Rheinland 2022, 2023, 2024 y 2025' },
    { metric: '100% SSO', label: 'Auditorías mineras BHP Spence y AMSA Centinela + 100% en auditorías cruzadas en terreno' },
    { metric: 'KPI verdes', label: '100% en KPI de indicadores verdes e imagen corporativa de flotas 2022-2025' },
    { metric: '100% F30', label: '100% cumplimiento F30 y F30-1 — antecedentes laborales y previsionales (recursos humanos), FTE BHP, jornada y libreta' },
    { metric: 'CLOA/SMAS', label: 'Acreditación y cumplimiento CLOA (BHP) y SMAS (AMSA) en contratos ENEX/RCL' },
    { metric: '100% KPI', label: 'Cumplimiento del KPI esperado para carga, traslado y descarga de producto' },
    { metric: '100%', label: 'Cumplimiento controles alcohol/drogas 2022-2025' },
    { metric: 'Simulacros', label: 'Diseño y dirección de simulacros masivos de combustible para gran minería' },
    { metric: 'Ley Emilia', label: 'Reconocimiento por incorporación de Ley Tolerancia Cero y Ley Emilia' },
    { metric: 'CIM BHP', label: 'Representante ENEX ante BHP Spence en Gestión Integrada de Contratistas y Plan de Ejecución de Contratos' },
    { metric: '+90%', label: 'Mejora en tiempos de llegada Viggo Chile zona norte 2021-2022' },
    { metric: '40% → 0%', label: 'Reducción de incidentes Viggo zona norte vía controles y auditorías' },
    { metric: '+60%', label: 'Incremento de volumen operado Viggo + 8 puntos de satisfacción de clientes' },
    { metric: '1eros eléctricos', label: 'Primeros buses 100% eléctricos King Long XMQ 6130 eTech (~280 km) para SQM' },
    { metric: '4 ISO', label: 'Cuatrinorma 9001 · 14001 · 45001 · 39001 (Transportes Hualpén)' },
    { metric: '70 contratos', label: '~28% de la cartera nacional (70 de 250 contratos) liderados en zona norte con operación 24/7 (Hualpén)' },
    { metric: '10.000', label: 'Pasajeros diarios bajo gestión zona norte (de 75K nacionales)' },
    { metric: 'Hualpén Digital', label: 'Liderazgo 2019-2021 como precursor de transformación digital zona norte' },
    { metric: '0 accidentes', label: 'Flota Calama 2019 (Hualpén)' },
    {
      metric: 'Inclusión femenina',
      label:
        '8,61% de mujeres en dotación nacional Hualpén — incorporación masiva en contratos Codelco y demanda relevante en principales contratos de Calama',
    },
    { metric: '15.000 m²', label: 'Layout cross docking implementado en Michelin Antofagasta/Mejillones' },
    { metric: '100% ↓', label: 'Reducción de incidentes en seguridad y medio ambiente — Copec Tocopilla' },
    { metric: '30% ↓', label: 'Ahorro de costos operativos en almacenamiento Copec Tocopilla' },
    { metric: '+90%', label: 'Precisión de inventarios Komatsu Cummins vía SAP MMS/WMS + radiofrecuencia' },
    { metric: '80% ↓', label: 'Reducción de costos logísticos CD La Negra (Komatsu)' },
    { metric: '70K+ SKU', label: 'Números de parte línea Cummins bajo gestión (Komatsu)' },
    { metric: '1eros CAEX', label: 'Recepción y logística de primeros camiones autónomos CAEX para minería chilena' },
    { metric: '90%', label: 'Estabilidad laboral Komatsu con mejoras en alimentación, transporte, vestuarios y áreas verdes' },
  ],
  experience: [
    {
      period: 'Dic 2025 – Actualidad',
      role: 'Ingeniero Especialista Independiente · Asesor de Operaciones Logísticas',
      company: 'Proyecto Freelance',
      location: 'Minería industrial, transporte, CD, maquinaria y cadena de suministro',
      scope:
        'Asesoría especializada en operaciones logísticas para minería industrial, transporte, centros de distribución, maquinaria, cadena de suministro, seguridad y acreditación de empresas, personas y flotas.',
      highlights: [
        'Soporte en diseño de procesos, control documental y revisión operacional para servicios mineros e industriales.',
        'Continuidad de suministro, cumplimiento normativo y seguridad operacional.',
        'Proyectos de mejora, control de riesgos, KPI, control contractual, planificación de transporte y administración de flotas.',
      ],
    },
    {
      period: '2022 – 2025',
      role: 'Administrador General de Proyecto · Jefe de Centro de Distribución y Logística Minera',
      company: 'ENEX S.A. / RCL S.A.',
      logos: ['enex', 'rcl'],
      location: 'BHP Spence · AMSA Centinela · Nueva Centinela',
      scope:
        'Administración general de contratos mineros de abastecimiento de combustible industrial para Minera Centinela AMSA, Nueva Centinela AMSA y BHP Spence; dirección de operaciones en Calama, Antofagasta, Sierra Gorda y Mejillones.',
      highlights: [
        'Flota de 50+ camiones tracto New Actros 2022-2025 y 70+ semirremolques; 500.000 km mensuales / 6M km anuales.',
        '300.000+ m³ transportados anualmente y 6.000+ turnos entregados a la gran minería.',
        'Cero accidentes STP/CTP; 100% cumplimiento RECSS por 4 años consecutivos; auditorías TÜV 90-100%.',
        'Premios RAEV nacionales 2022-2025 y reconocimientos CONASET/CONACEP como flota más segura de Chile.',
      ],
      extended: [
        'Contratos secundarios: FCAB Calama/Train/Arriero/Mejillones/Antofagasta, Planta Terquim Mejillones, Planta Copec Mejillones, Planta AMSA Esperanza/Esperanza Sur, Minera Encuentro, AMSA Óxido, Planta SX BHP, Muelle AMSA y Caleta Michilla.',
        'Apoyo logístico internacional para proyecto Albemarle Perú Químico y proyecto Engie Gas Minería AMSA.',
        'Representación de ENEX/RCL ante mandantes en costos, cumplimiento, seguridad, mantenimiento, estados de pago, KPI, auditorías y planes de ejecución contractual.',
        'Cumplimiento WRAC EECC, DPRF EECC, RECSS EECC, declaraciones TC8/TC10 SEC para camiones tanque (DS160), Plan SSO, gestión de incidentes y estándar alcohol/drogas.',
        'KPI implementados: turnos, viajes disponibles, entregas reales petrolera/EDS/SGO/SX, viajes caídos/redestinados, m³ entregados, kilómetros, RAEV, Guardian, mantenimiento, charlas y liderazgos visibles.',
        'Acreditaciones MyPass, SAR, DLMS, LMS, DBMS, SIGA, SERCOL, AIRON, SAP; plataformas Seguridad Proactiva, Guardian, Migtra, Bureau Veritas, FuelTrack, Seeing Machine y Skynav.',
        'Cumplimiento CLOA (BHP) y SMAS (AMSA); aplicación de CIM Gestión Integrada de Contratistas para BHP Spence, Performance Meetings, Plan de Ejecución de Contratos y conductas esperadas AMSA.',
        'Diseño y dirección de simulacros masivos de combustible para gran minería con entidades públicas; reconocimiento por Ley Tolerancia Cero y Ley Emilia.',
        'Monitor de seguridad y operaciones; líder del departamento de higiene y seguridad; auditor interno hacia ingeniería del área.',
        '0% desviaciones por uso de celular; reducción secuencial de fatiga y somnolencia entre 2022 y 2025.',
        'Campañas comunitarias y control de medio ambiente con 100% de resultados satisfactorios.',
      ],
    },
    {
      period: '2021 – 2022',
      role: 'Gerencia de Operaciones Filial Viggo · Jefe de Sucursal Zonal',
      company: 'Viggo Chile S.A. / Tur Bus',
      logos: ['viggo', 'tur-bus'],
      location: 'Zona Norte · II Región Antofagasta',
      scope:
        'Responsable legal y operacional para contratos mineros en zona industrial minera del norte, transporte, flotas, mantenimiento, seguridad, logística y KPI.',
      highlights: [
        'Contratos mineros: Atacama Minerals, CTTO Lots, Finning MEL, Molyb (filial Codelco), Caserones, SAM, Orica Chile, FCAB, Toconao SQM, Excon y Franke.',
        '150 buses Mercedes-Benz O-500 RS/RSD con carrocería Irizar i6 y Busscar; 150 Sprinter 516 y Vito; primeros Sprinter 100% eléctricos 60 kWh.',
        'Sucursal Antofagasta 30.000+ m² con 300+ colaboradores; 500.000 km mensuales en gran minería.',
      ],
      extended: [
        'Reducción de incidentes de 40% a 0% mediante programas de control, auditorías y acciones correctivas.',
        'Mejora superior a 90% en tiempos de llegada y reducción de costos operativos hasta 80% por optimización de rutas.',
        '100% cumplimiento de auditorías y SLA en contratos clave; +60% volumen operado por expansión de flota y cobertura.',
        'Despliegue de primeros buses 100% eléctricos King Long XMQ 6130 eTech (autonomía ~280 km) para SQM.',
        'Sello Giro Limpio SQM, GTP Academia, GTP BCN School of Business, Programa de Liderazgo Viggo y 5 Reglas Operacionales.',
        'GTP — Grupo de Transportes Pasajeros; experiencia con chasis Scania y carrocería Marcopolo.',
        'Implementación 100% de controles Art. 25, velocidades, alcohol/drogas, fatiga y plataformas de control de flota.',
      ],
    },
    {
      period: '2019 – 2021',
      role: 'Jefe Zonal de Operaciones II Región · Gerente Subrogante CD',
      company: 'Transportes Hualpén S.A.',
      logos: ['hualpen'],
      location: 'Calama · Antofagasta · Iquique · Tarapacá',
      scope:
        'Gerencia de operaciones, transporte de pasajeros para minería industrial en zona industrial minera del norte, distribución, mantenimiento, logística, control de flota y administración de contratos.',
      highlights: [
        '70 contratos en zona norte (de 250 nacionales) con operaciones 24/7 para gran minería; 10.000 pasajeros diarios bajo gestión.',
        'Flotas Mercedes-Benz O-500 RS/RSD, Scania, Yutong, Volvo, Marcopolo, King Long; 300 buses, 100 Sprinter, 150 minibuses, 150 microbuses.',
        'Certificación ISO 39001 Seguridad Vial sumando cuatrinorma con ISO 9001/14001/45001.',
      ],
      extended: [
        'Contratos: Finning, Enaex, Codelco División Gabriela Mistral, Komatsu, CVV, Chuquicamata, Ministro Hales, Albemarle, Teck QB1/QB2, Bechtel, Compass Group, Sodexo y Besalco.',
        'Reducción de incidentes 90% y reducción de costos operativos 60% con KPI de disponibilidad y eficiencia.',
        'Incorporación de Mobileye, telemetría, control de tráfico, control de pasajeros, control de somnolencia y checklist digital.',
        'Primer reporte de sostenibilidad Hualpén 2020; precursor de electromovilidad y energías renovables en zona norte.',
        'Escuela de Conductores en Calama junto a sindicatos; incorporación masiva de mujeres a contratos Codelco, alcanzando 8,61% de mujeres en dotación nacional y demanda relevante en principales contratos de Calama.',
        'Cero accidentes flota Calama 2019; participación en transformación digital Hualpén Digital 2019-2021.',
        'Supervisión de más de 100 contratos mineros y locales, 14 prevencionistas de riesgos y 10 administradores de contrato.',
        'Cumplimiento de EBITDA, reporting a directorio y atributos del Servicio Hualpén: seguridad, confort, innovación, puntualidad y tecnología.',
        'Escuela de Conductores en Calama con certificación Automóvil Club de Chile.',
      ],
    },
    {
      period: '2018 – 2019',
      role: 'Gerente de Operaciones Centro de Distribución',
      company: 'Michelin / Hellmann International / Cademartori',
      logos: ['michelin', 'ati', 'epa', 'puerto-angamos'],
      location: 'Antofagasta · Mejillones',
      scope:
        'Recepción portuaria, desconsolidación, almacenamiento y distribución de neumáticos para equipos y componentes mineros.',
      highlights: [
        'Sucursal 30.000+ m² con 250+ transportistas externos, administración y planta.',
        'Implementación de sistema automatizado de stock y layout 15.000 m² para cross docking.',
        'Asesoría en Mega Proyecto Planta de Residuos Industriales de Caucho Michelin Internacional.',
      ],
      extended: [
        'Gestión de puertos ATI, EPA, Puerto Angamos (PA) y SAA; estiba de contenedores de 40 pies, Open Top, ramplas y cargas sobredimensionadas.',
        'Control de costos operativos y aplicación de Incoterms EXW/FCA/CPT/CIP/DAP/DPU/DDP/FAS/FOB/CFR/CIF.',
        'Manejo de contenedores 20/40 pies, Dry Van, Reefer, High Cube, Open Top, Flat Rack y Tank.',
        'Cumplimiento Ley 20.123, Ley 16.744, DS 594 y DS 148; gestión SIDREP y KPI de accidentabilidad.',
        'Layout para neumático Michelin XDR3 59/80R63 (CAT 797B), diámetro 4,2 m, stock superior a 1.000 unidades.',
      ],
    },
    {
      period: '2014 – 2017',
      role: 'Gerente · Subgerente de Operaciones · Jefe Regional',
      company: 'Orica Chile · Enaex · Maxam · Vinara · Transportes Cinco',
      logos: ['orica', 'enaex', 'maxam', 'vinara', 'transportes-cinco'],
      location: 'II Región',
      scope:
        'Recepción portuaria, desconsolidación, almacenamiento y distribución de explosivos y detonadores bajo Ley 17.798 de Control de Armas y Explosivos.',
      highlights: [
        'Transición de contrato Transportes Cinco (15.000 m²) a Vinara (30.000 m²) con continuidad solicitada por clientes.',
        'Liderazgo de equipos multidisciplinarios +100 personas en alta presión y riesgo; operación 24/7.',
        'Coordinación de convoyes con escolta armada (ex FF.AA. y Carabineros) bajo Guías de Libre Tránsito.',
      ],
      extended: [
        'Contratos: Orica Chile y servicios SPOT para Minera Centinela, Zaldívar, Antucoya y Polytex.',
        'Control de stock y trazabilidad de Cordtex, Exel, Pentex, detonadores eléctricos y tecnologías EBS, 4D, WebGen y RHINO.',
        'Custodia de emulsiones gasificadas, productos químicos de alto riesgo y cianuro bajo protocolos de seguridad nacional.',
        'Gestión de residuos según DS 148/2003 MINSAL; supervisión de Reach Stackers, grúas horquilla y camiones especiales.',
        'KPI de OTIF, seguridad, disponibilidad de flota, gastos generales, presupuestos operativos y rentabilidad.',
      ],
    },
    {
      period: '2011 – 2013',
      role: 'Jefe de Planta y CD · Gerencia de Operaciones y Abastecimiento',
      company: 'Copec S.A. / Engie',
      logos: ['copec', 'engie'],
      location: 'Tocopilla',
      scope:
        'Dirección de operaciones, transporte y abastecimiento de combustibles líquidos para gran minería y sector energético.',
      highlights: [
        'Sucursal y planta 30.000 m² con 100+ colaboradores; carga/descarga de buques tanque en Puerto PC6 Banker.',
        'Reducción 100% en incidentes de seguridad y medio ambiente; 30% de ahorro en costos operativos.',
        'Alianza estratégica Copec-minería con representación corporativa en Tocopilla.',
      ],
      extended: [
        'Implementación DS 160 combustibles líquidos, DS 148 residuos peligrosos y Ley 16.744 SSO.',
        'Control de stock y trazabilidad de petróleo diesel, PC6, JET A1 y lubricantes industriales.',
        'Mediciones en tanques verticales para suministro a plantas generadoras y faenas mineras.',
        'Modernización de instalaciones de combustible y atención al cliente 24/7.',
        'Cero pérdidas en abastecimiento; operación de bombeo en terminales marítimos PC6 Banker.',
        'Representación activa de Copec S.A. en Tocopilla y generación de valor socioeconómico compartido.',
      ],
    },
    {
      period: '2008 – 2011',
      role: 'Jefe de Operaciones Centro de Distribución Zona Norte',
      company: 'Komatsu Cummins Chile S.A.',
      logos: ['komatsu'],
      location: 'Antofagasta',
      scope:
        'Dirección de operaciones para recepción portuaria, desconsolidación, almacenamiento y distribución de equipos, componentes y repuestos críticos para gran minería.',
      highlights: [
        '70.000+ números de parte de línea Cummins bajo gestión; mejora 90% en precisión de inventarios mediante RF.',
        'Implementación SAP MMS/WMS y radiofrecuencia; reducción 80% en costos logísticos en CD La Negra.',
        'Logística y recepción de los primeros camiones autónomos CAEX para minería chilena.',
      ],
      extended: [
        'Traslado estratégico CD La Portada Norte → CD La Negra → CD La Portada Antofagasta.',
        'Supervisión de 5.000 m² de componentes mayores y despiece; armado, traslado, patio y entrega final.',
        '90% de estabilidad laboral con mejoras en alimentación, transporte, vestuarios y áreas verdes.',
        'Lean Logistics: estanterías, racks, cross docking, picking, packing, FIFO, LIFO, FEFO y OTIF.',
        'Programa Un Paso Más Adelante; certificación interna en equipos de alto tonelaje (3,5 a 15 ton).',
        'Gestión de KPI, CAPEX y 100% de cumplimiento en planes de mejoramiento continuo validados por clientes estratégicos.',
        'Logística inversa, remanufactura y certificación interna en equipos de 3,5 a 15 toneladas.',
      ],
    },
    {
      period: '2005 – 2008',
      role: 'Líder de Operaciones de Planta · Gerencia de Operaciones Productos Terminados',
      company: 'SQM – Sociedad Química y Minera de Chile S.A.',
      logos: ['sqm'],
      location: 'Coya Sur · María Elena · Pedro de Valdivia · Tocopilla Port',
      scope:
        'Operaciones multimodales terrestres, ferroviarias y portuarias para recepción de materia prima, almacenamiento y distribución internacional de nitratos y sulfatos.',
      highlights: [
        'Plantas Prilado, Sulfato, Granulación, KCL, Secado KNO3, canchas de acopio y Puerto Tocopilla.',
        'Coordinación de despachos por ferrocarril, camiones y tráfico marítimo para exportación.',
      ],
      extended: [
        'Gestión de stock y despacho de KNO3, KCL, sulfatos y fertilizantes NPK.',
        'Implementación de protocolos de seguridad química, limpieza industrial y prevención de contaminación cruzada.',
        'Dirección desde sala de control con monitoreo de variables críticas, muestreos y análisis químico en tiempo real.',
        'Coordinación de correas transportadoras, trenes de alta capacidad, secadores industriales y ensacado automático.',
      ],
    },
    {
      period: 'Formación militar · Titulado con máxima distinción',
      timelineMark: '0',
      role: 'Oficial de Ejército en Ciencias Militares',
      company: 'Ejército de Chile',
      logos: ['ejercito-chile'],
      location: 'Chile',
      scope:
        'Formación y desempeño como Oficial de Ejército en Ciencias Militares en el Ejército de Chile; titulado con máxima distinción. Base de la trayectoria en operaciones cívico-militares, logística, transporte y abastecimiento.',
      highlights: [
        'Intendencia, Inteligencia, logística, transporte, abastecimiento, cadena de suministro y operaciones.',
        'Titulado con máxima distinción — Oficial de Ejército de Chile en Ciencias Militares.',
        'Operaciones cívico-militares e infraestructura logística como fundamento de la carrera en gran minería del norte.',
      ],
      extended: [
        'Formación en intendencia, inteligencia, logística militar, transporte, abastecimiento y cadena de suministro.',
        'Base de liderazgo en operaciones de alta exigencia, disciplina operacional y continuidad de servicio.',
      ],
    },
  ],
  gallery: getGalleryItems('es'),
  education: [
    {
      title: 'Magíster en Dirección de Operaciones y Logística',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2024 – 2026',
      status: 'in_progress',
      detail: 'Postgrado, Facultad de Educación y Ciencias Sociales. Folio 3320571. Término estimado: noviembre 2026.',
    },
    {
      title: 'Diplomado en Gestión de Personas y Cambio Organizacional',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2023 – 2024',
      status: 'titled',
      detail:
        'Postítulo, Facultad de Educación y Ciencias Sociales. Registro 588/2023, Reg. 2024 N°7031. Titulado con máxima distinción.',
      recognition: 'Certificado de reconocimiento a mejor rendimiento académico nacional.',
    },
    {
      title: 'Diplomado en Gestión Logística y Cadena de Suministro',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2025 – 2026',
      status: 'in_progress',
      detail: 'Postítulo, Facultad de Ingeniería. Folio 3320571. Término estimado: agosto 2026.',
    },
    {
      title: 'Diplomado en Liderazgo para la Innovación',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2025 – 2026',
      status: 'in_progress',
      detail: 'Postítulo, Facultad de Ingeniería. Folio 3320571. Término estimado: noviembre 2026.',
    },
    {
      title: 'Diplomado en Dirección de Operaciones',
      institution: 'Universidad Andrés Bello',
      logo: 'unab',
      period: '2025 – 2026',
      status: 'titled',
      magna: true,
      detail: 'Postítulo, Facultad de Ingeniería. Folio 3789769. Titulado marzo 2026.',
      recognition: 'Distinción Magna Cum Laude',
      recognitionDetail:
        'Máximo honor académico del postítulo. Magna Cum Laude es una distinción universitaria de uso internacional que reconoce a titulados con desempeño excepcional: excelencia sostenida y promedio muy superior al estándar del programa. En la escala clásica de honores académicos se sitúa por encima de cum laude; en este diplomado certificó el más alto nivel de distinción alcanzable.',
    },
    {
      title: 'Oficial de Ejército de Chile en Ciencias Militares',
      institution: 'Ejército de Chile',
      logo: 'ejercito-chile',
      status: 'titled',
      detail:
        'Intendencia, Inteligencia, logística, transporte, abastecimiento, cadena de suministro y operaciones. Titulado con máxima distinción.',
    },
    {
      title: 'Ingeniero en Administración Logística',
      institution: 'Universidad Estatal Arturo Prat',
      logo: 'unap',
      status: 'titled',
      detail: 'Facultad de Ciencias Empresariales. Registro 19303029. Titulado con máxima distinción.',
    },
    {
      title: 'Experto AN/T en Prevención de Riesgos',
      institution: 'Universidad Andrés Bello / AIEP',
      logo: 'unab',
      status: 'titled',
      detail: 'Escuela de Ingeniería y Construcción. Registro 105792. Res. 3314 SNS AN/T-4431. Titulado con máxima distinción.',
    },
    {
      title: 'Técnico en Electromecánica',
      institution: 'Liceo Técnico Profesional María Egaña',
      status: 'titled',
      detail: 'Educación media técnico profesional. Titulado con máxima distinción.',
    },
    {
      title: 'Educación Básica',
      institution: 'Colegio Unión Nacional Árabe',
      status: 'completed',
      detail: 'Formación escolar completa.',
    },
  ],
  drivingLicenses: [
    {
      license: 'Licencia clase A-2',
      description:
        'Conducción profesional SERCAEM — vehículos motorizados de carga, transporte crítico y operación en entornos industriales.',
    },
    {
      license: 'Licencia clase D',
      description:
        'Conducción profesional SERCAEM — maquinaria automotriz pesada: tractores, grúas horquilla, retroexcavadoras, palas mecánicas, aplanadoras y bulldozer. No habilita automóviles, camionetas ni motos.',
    },
  ],
  certifications: [
    {
      category: 'Acreditaciones mineras e ingenieriles',
      items: [
        'Ingeniero Especialista en Sistemas CAS para flotas de transporte crítico, combustibles, pasajeros y químicos.',
        'Ingeniero Experto en Acreditación BHP/AMSA: SIGA, RECSS Centinela, Aureon, MyPass, LMS y SAR.',
        'Experto SERCOL BHP/AMSA en gestión de subcontratistas y carpetas de arranque (CEP).',
        'Administrador BHP DBMS/iButton, PSGCC, PTP y SKYNAV para control de identidad y conducción.',
        'Procesos de acreditación de empresas, personas y flotas en plataformas mineras.',
      ],
    },
    {
      category: 'Certificaciones técnicas y maquinaria pesada',
      items: [
        'Ingeniero Monitor UATSA (Universidad de Antofagasta): cargadores frontales, retroexcavadoras y grúas horquilla 3-15 ton.',
        'Operador especialista en Reach Stackers, apiladores eléctricos para racks de 12 m y montacargas UATSA.',
        'Instructor en 5 Reglas Operacionales de Conducción.',
      ],
    },
    {
      category: 'Normativas y compliance legal',
      items: [
        'Ley 16.744 (accidentes del trabajo y enfermedades profesionales), Ley 20.123 (subcontratación), Ley 17.798 (explosivos).',
        'Ley Karin (Ley 21.643 — acoso laboral, violencia y discriminación en el trabajo).',
        'DS 132, DS 160 (art. 184 — compartimientos de camiones tanque), DS 148, DS 594, DS 40 (art. 21).',
        'Art. 25 bis y Art. 22 bis; RESPEL, SIDREP, WRAC, DPRF, RECSS, PREXOR, PLANESI, CEAL-SM, HCR, SSO y HSE.',
        'Auditor Interno SGI: ISO 9001, ISO 14001 y OHSAS 18001.',
        'Protocolos PREXOR (ruido), PLANESI (silicosis), gestión de riesgos psicosociales CEAL-SM.',
        'Instructor en manejo a la defensiva, conductas críticas y autoprotección CELACOP.',
        'Especialista en prevención de fatiga, somnolencia, riesgos UV, térmicos, viales y continuidad operacional.',
      ],
    },
    {
      category: 'Sistemas de gestión ISO',
      items: [
        'ISO 9001 Calidad.',
        'ISO 14001 Medio Ambiente.',
        'ISO 45001 Seguridad y Salud Ocupacional.',
        'ISO 39001 Seguridad Vial.',
        'Auditor interno certificado.',
      ],
    },
    {
      category: 'Liderazgo estratégico y gestión del cambio',
      items: [
        'Programa de Liderazgo Ejecutivo Viggo: Accountability, Metodologías Ágiles, Ética, Transformación Digital.',
        'GTP Academia y GTP BCN School of Business: ética, transformación digital, metodologías ágiles y accountability.',
        'Gestión del Cambio Hualpén Digital.',
        'Desarrollo Organizacional y Relaciones Laborales — talleres de contratación de subcontratistas y técnicas UATSA.',
      ],
    },
  ],
  tools: [
    {
      category: 'ERP y sistemas logísticos',
      items: [
        'SAP nivel experto: SAP MM, SAP PM, SAP WMS, SAP FI, SAP MMS/WMS, SAP Business One, radiofrecuencia RF, ubicaciones, control de SKU, rebajes y trazabilidad.',
        'Transacciones SAP LT12 (confirmación de orden de transporte WM), LT15 (cancelación OT) y MIGO (movimientos de mercancías: entradas, salidas y traslados).',
        'ERP BERMAT, Bertrams, Rumba Logistics, Informat y Simatrans.',
        'WMS, inventarios cíclicos/ciegos/trimestrales/semestrales/anuales, picking, packing, cross docking, FIFO, FEFO, LIFO y OTIF.',
      ],
    },
    {
      category: 'Telemetría, seguridad proactiva y control de flota',
      items: [
        'Guardian Seeing Machines (fatiga y somnolencia).',
        'Tecnología REP SQM (experiencia profesional de 3 años en operaciones de planta).',
        'Salas de control: variables críticas, reportabilidad de procesos y continuidad de producción.',
        'Migtra (navegador táctico y control operacional).',
        'Wisetrack, FuelTrack, Skynav, Mobileye, DBMS/iButton y sistemas RAEV.',
        'Control de sustancias peligrosas con FuelTrack para cisternas de combustible y ácido.',
        'Control de velocidad, uso de celular, alcohol/drogas, checklist digital, control de pasajeros, georreferenciación, planificación de viajes y cartas de viaje.',
      ],
    },
    {
      category: 'Plataformas mineras y de acreditación',
      items: [
        'MyPass, SAR, DLMS, LMS, DBMS, SIGA, SERCOL, AIRON.',
        'CESMEC, Bureau Veritas, TÜV Rheinland.',
        'Control CAS, Araya y Briones, Directic AMSA, RECSS, PGR, PSGCC, PTP y CC.',
      ],
    },
    {
      category: 'Puertos, contenedores y cargas especiales',
      items: [
        'Terminales ATI, EPA, Puerto Angamos (PA) y SAA — recepción portuaria y desconsolidación.',
        'Estiba de contenedores de 40 pies, Open Top, Flat Rack, Dry Van, Reefer y High Cube.',
        'Ramplas, cargas sobredimensionadas, tuberías industriales y neumáticos de gran dimensión.',
        'Incoterms EXW, FCA, CPT, CIP, DAP, DPU, DDP, FAS, FOB, CFR y CIF.',
      ],
    },
    {
      category: 'Informática profesional',
      items: [
        'Microsoft Excel avanzado — reportabilidad y análisis de KPI.',
        'Microsoft Word y Outlook avanzado — gestión operacional y seguimiento de indicadores.',
      ],
    },
  ],
  languages: [
    'Español: nativo.',
    'Inglés: nivel medio conversacional y nivel alto para traducción técnica.',
  ],
};
