/** English captions - index-aligned with gallery.manifest.json */
export const galleryCaptionsEn: string[] = [
  "Cross-audit of contractor personnel — sulfide oil plant, Antofagasta Minerals",
  "Industrial fuel supply audit — heavy equipment, AMSA Antofagasta Minerals",
  "Visible engineering leadership — cross inspection at Antofagasta Minerals oil plants",
  "BHP — heavy equipment inspection, CAS system",
  "Engineering route monitoring — logistics traffic control, BHP Spence supply",
  "Chilean Army officers training",
  "Army",
  "Operations manager Cademartori — creator of the Michelin distribution center, international Hellmann Mejillones project for the world’s largest tires with Finning OC",
  "Northern Zone operations manager — international imports, Cademartori projects, world’s largest Russian aircraft for mining project supplies, Calama Airport, Chile",
  "Operations manager — Orica project, international maritime dispatch of explosive materials",
  "International project manager — Changay Chile cargo for mining supply, 250 carriers, round trip, EXW",
  "Lead logistics process engineer — major northern contracts; large-scale talks for Hualpén industrial and mining operations staff in Calama",
  "Lead engineer — highest-impact drill in the Antofagasta region for route accidents and collisions; Fire Service, Carabineros, PDI, municipal security",
  "Logistics engineers — thesis project, Universidad Estatal Arturo Prat, Chile, Faculty of Business Sciences",
  "Northern Zone fuel supply and distribution project launch — ENEX S.A. specialist and contractor presentation",
  "Cabinet inspections — road safety elements, Northern Zone, Chile",
  "Control room and process manager — SQM prill plant, Coya Sur, one of the world’s largest saltpetre plants, María Elena, Antofagasta, Chile",
  "Shift manager — plant operations, shipping and finished products, SQM María Elena plants (granulation, sulfate, KNO3 drying, prill, NPK and others)",
  "Distribution center lead — Komatsu Cummins Chile; storage, distribution, fleets, machinery, cross-docking, picking, packing, inventories, SAP and others",
  "Labor climate lead — sports activities, Escondida mine project",
  "Route loading control lead — cross leadership for heavy-equipment operational deviation recognition, Codelco Chile",
  "New ENEX and BHP alliance lead — Mercedes-Benz New Actros 2025 fleet for industrial and mining supply",
  "Operations and branch lead — Second Region; labor climate, inclusion, safety and environment, Viggo Chile Tur Bus",
  "Project lead — industrial and mining supply, logistics, distribution and storage during conflicts, desert routes",
  "Test lead — CAEX equipment disassembly for future dispatch via differentials for large-scale mining and future autonomous truck assembly for Codelco",
  "Safe route recognition lead — contractor safe fleet routes, interior mining",
  "Mass drill lead — operations, safety and administration for large-scale mining",
  "24/7 mass logistics supply lead for large-scale mining — Atacama Desert, ENEX S.A.",
  "Regional operations lead — Northern Zone Viggo Chile Tur Bus for large-scale mining; labor climate celebration, Antofagasta Region, teamwork, northern mining contracts",
  "Field leadership on route — cab inspection, mining fuel supply transport",
  "Cross leadership with Chilean Fire Service — emergency processes on route, mining, public and private areas",
  "Cross leadership with BHP principal and contract administration — labor climate and client satisfaction, BHP Spence",
  "Cross leadership with mining shift managers — hygiene and safety audit, SX plant, BHP Spence",
  "Night leadership — legal document inspection for chemical transport on route, large-scale mining",
  "Visible leadership at oil plants — Encuentro, sulfides, oxide, Esperanza Sur, Esperanza, pier, Romanas, Antofagasta Minerals",
  "Continuous improvement for distribution contract staff — Northern Zone Industrial ART 25 Bis, ENEX BHP Spence",
  "Lead operator — SQM, labor climate with contractor personnel, María Elena, Coya Sur, Chile",
  "Driver recognition for best practices in liquid fuel tanker driving procedures — AMSA Centinela project",
  "Recognition for safety, driving and supervision staff — best RAEV 2024 “yo me cuido” campaigns",
  "Monthly HSE meeting — Antofagasta Minerals supply",
  "Quarterly meeting — northern administration and specialists, SSMA northern supply projects for large-scale mining",
  "Route follow-up — RAEV control, ENEX S.A. industrial mining project",
  "Mass drill — Mejillones Fire Company, sulfuric acid; learning exchange for contract administration, mining incidents",
];
